data <- c(12, 15, 18, 20, 22, 25, 28, 30, 32, 35)
iqr_value <- IQR(data)
range_value <- max(data) - min(data)
quintiles <- quantile(data, probs = seq(0, 1, by = 0.25))
summary_stats <- summary(data)
cat("Interquartile Range (IQR):", iqr_value, "\n")
cat("Range:", range_value, "\n")
cat("Quintiles:", quintiles, "\n")
cat("Summary Statistics:\n", summary_stats)